version: '3.8'
services:
    juicefs:
        image: juicefs
        command: >
            juicefs format --storage s3
                  --bucket ${OBJECT_STORAGE_BUCKET}
                  --access-key ${JUICEFS_ACCESS_KEY}
                  --secret-key ${JUICEFS_SECRET_KEY}
                  ${DATABASE_URL}
                  ${OBJECT_STORAGE_DIRECTORY}
        environment:
            - AWS_DEFAULT_REGION=${REGION}
        volumes:
            - ./mnt/jfs:/mnt/jfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        security_opt:
            - apparmor:unconfined
